name: autofix.ci

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run biome with auto-fix
        run: npm run lint-biome
        continue-on-error: true

      - name: Run oxlint with auto-fix
        run: npm run lint-oxlint
        continue-on-error: true

      - name: Fix website client linting
        working-directory: website/client
        run: |
          npm ci
          npm run lint
        continue-on-error: true

      - name: Fix website server linting
        working-directory: website/server
        run: |
          npm ci
          npm run lint
        continue-on-error: true

      - name: Fix browser extension linting
        working-directory: browser
        run: |
          npm ci
          npm run lint
        continue-on-error: true

      - uses: autofix-ci/action@635ffb246a1a6e4e4066a21a6b7e03c97c2ba9cf